repositories:
  - name: keel
    url: https://charts.keel.sh

releases:
  # -----------------------------
  # -- Keel
  # -----------------------------
  - name: keel
    installed: true
    namespace: keel-system
    createNamespace: true
    chart: keel/keel
    version: 0.9.11
