repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true

releases:
  - name: argocd
    installed: true
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: 5.23.3
    values:
      - server:
          extraArgs:
            - --insecure
  
  - name: redis
    installed: true
    chart: bitnami/redis
    version: 17.13.1
